link_tastic_main/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('linktastic.urls'))
]

linktastic/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", views.home, name='home'),
    path("your-links/", views.your_links, name='your-links'),
    path("url-shortener/", views.url_shortener, name='url-shortener'),
    path("settings/", views.settings, name='settings'),
    path("customize-links/", views.customize_links, name='customize-links'),
    path("customize-profile/", views.customize_profile, name='customize-profile'),
    path("register/", views.register, name="register"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path('delete_link/<int:link_id>', views.delete_link, name='delete-link'),
    path('u/<str:username>', views.public_profile, name='public-profile'),
    path('edit-profile/', views.edit_profile, name='edit-profile'),
    path('change_password/', auth_views.PasswordChangeView.as_view(template_name='linktastic/change_password.html'), name='change_password'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='linktastic/password_change_done.html'), name='password_change_done'),
    path('<str:slug>', views.redirect_view, name='redirect')
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

linktastic/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

BASE62_ALPHABET = "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"

def base62_encode(num, alphabet=BASE62_ALPHABET):
    """Encode a positive number in Base X

    Arguments:
    - `num`: The number to encode
    - `alphabet`: The alphabet to use for encoding
    """
    if num == 0:
        return alphabet[0] * 7
    arr = []
    base = len(alphabet)
    while num:
        num, rem = divmod(num, base)
        arr.append(alphabet[rem])
    arr.reverse()
    encoded = ''.join(arr)
    while len(encoded) < 7:
        encoded = '0' + encoded
    return encoded

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.userprofile.save()

class Link(models.Model):
    title = models.CharField(max_length=200)
    url = models.URLField()

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    links = models.ManyToManyField(Link)
    display_name = models.CharField(max_length=200, blank=True)
    bio = models.TextField(blank=True)
    profile_picture = models.ImageField(upload_to='profile_pictures', blank=True)

BUTTON_SHAPES = [
    ('SQUARE', 'Square'),
    ('ROUNDED', 'Rounded'),
]

ICONS = [
    ('NONE', 'None'),
    ('STAR', 'Star'),
    ('HEART', 'Heart'),
]

FONT_SIZES = (
    ('12px', 'Small'),
    ('16px', 'Medium'),
    ('20px', 'Large'),
)

FONT_COLORS = (
    ('black', 'Black'),
    ('blue', 'Blue'),
    ('red', 'Red'),
)


class UserLinkDisplayPreference(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    font_size = models.CharField(max_length=10, choices=FONT_SIZES, default='16px')
    font_color = models.CharField(max_length=10, choices=FONT_COLORS, default='black')
    font = models.CharField(max_length=100, default='default_font')
    button_shape = models.CharField(max_length=10, choices=BUTTON_SHAPES, default='SQUARE')
    icon = models.CharField(max_length=10, choices=ICONS, default='NONE')

    class Meta:
        verbose_name_plural = "User link display preferences"

class ShortenedURL(models.Model):
    id = models.AutoField(primary_key=True)  
    original_url = models.URLField()
    slug = models.CharField(max_length=20, null=True)

    def generate_slug(self):  
        return base62_encode(self.id)  

linktastic/forms.py
from django import forms
from .models import Link, UserProfile, UserLinkDisplayPreference
from django.core.exceptions import ValidationError
from urllib.parse import urlparse

class LinkForm(forms.ModelForm):
    url = forms.URLField(widget=forms.TextInput) # Override the URL field with client side validation disabled
    class Meta:
        model = Link
        fields = ['title', 'url']

    def clean_url(self):
        url = self.cleaned_data.get('url')
        if url:
            if '://' not in url:
                # Prepend 'http://' if no scheme (http, https, ftp, etc.) is provided
                url = 'http://' + url
            parsed = urlparse(url)
            if not bool(parsed.netloc) and bool(parsed.path):
                # If the url is still invalid, raise a validation error
                raise ValidationError('Please enter a valid URL')
        return url
    
class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['display_name', 'bio', 'profile_picture']

class UserLinkDisplayPreferenceForm(forms.ModelForm):
    class Meta:
        model = UserLinkDisplayPreference
        fields = ['font_size', 'font_color', 'button_shape', 'icon']

class URLShortenerForm(forms.Form):
    original_url = forms.URLField(widget=forms.TextInput)

    def clean_original_url(self):
        original_url = self.cleaned_data.get('original_url')
        if original_url:
            if '://' not in original_url:
                original_url = 'http://' + original_url
            parsed = urlparse(original_url)
            if not bool(parsed.netloc) and bool(parsed.path):
                raise forms.ValidationError('Please enter a valid URL')
        return original_url

linktastic/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib import messages
from django.contrib.auth.models import User

from django.http import HttpResponseRedirect, Http404, HttpResponse
from django.urls import reverse
from django.conf import settings

from .forms import LinkForm, UserProfileForm, UserLinkDisplayPreferenceForm, URLShortenerForm
from .models import Link, UserProfile, UserLinkDisplayPreference, ShortenedURL

# Create your views here.

def login_required_message(function):
    def wrap(request, *args, **kwargs):
        if request.user.is_authenticated:
            return function(request, *args, **kwargs)
        else:
            messages.info(request, "You must be logged in to do that.")
            return HttpResponseRedirect(reverse(settings.LOGIN_URL))
    wrap.__doc__ = function.__doc__
    wrap.__name__ = function.__name__
    return wrap

def home(request):
  return render(request, 'linktastic/home.html')

@login_required_message
def your_links(request):
    if request.method == 'POST':
        form = LinkForm(request.POST)
        if form.is_valid():
            link = form.save()
            profile = UserProfile.objects.get(user=request.user)
            profile.links.add(link)
            messages.success(request, 'Link added successfully.')
            return redirect('your-links')
    else:
        form = LinkForm()

    profile = UserProfile.objects.get(user=request.user)
    links = profile.links.all()
    return render(request, 'linktastic/your-links.html', {'form': form, 'links': links})

@login_required_message
def settings(request):
  return render(request, 'linktastic/settings.html')

@login_required_message
def url_shortener(request):
  return render(request, 'linktastic/url-shortener.html')

@login_required_message
def customize_links(request):
  return render(request, 'linktastic/customize-links.html')

@login_required_message
def customize_profile(request):
  return render(request, 'linktastic/customize-profile.html')

def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        username = form.data.get('username').lower()  # Get the lowercased username
        form.data = form.data.copy()  # Make a copy
        form.data['username'] = username  # Replace the username with the lowercased username
        if form.is_valid():
            form.save()
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            login(request, user)
            messages.success(request, 'Registration successful.')
            default_pref = UserLinkDisplayPreference(user=user, font_color='black', font_size='Medium')
            default_pref.save()
            return redirect('your-links')
    else:
        form = UserCreationForm()
    return render(request, 'linktastic/register.html', {'form': form})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        username = form.data.get('username').lower()
        form.data = form.data.copy()
        form.data['username'] = username
        if form.is_valid():
            password = form.cleaned_data.get('password')
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                messages.success(request, 'Login successful.')
                return redirect('your-links')
        else:
            pass
    else:
        form = AuthenticationForm()
    return render(request, 'linktastic/login.html', {'form': form})

def logout_view(request):
    logout(request)
    messages.success(request, 'Logged out successfully.')
    return redirect('home')

@login_required_message
def delete_link(request, link_id):
    link = Link.objects.get(pk=link_id)
    if request.user.userprofile.links.filter(pk=link_id).exists():
        request.user.userprofile.links.remove(link)
        messages.success(request, 'Link deleted successfully.')
        return redirect('your-links')
    else:
        messages.error(request, 'Link not found.')
        return redirect('your-links')
    
def public_profile(request, username):
    user = User.objects.get(username=username)
    user_profile = UserProfile.objects.get(user=user)
    links = user.userprofile.links.all()
    user_pref = UserLinkDisplayPreference.objects.get(user=user)
    return render(request, 'linktastic/public_profile.html', {'username': username, 'links': links, 'user_profile': user_profile, 'user_pref': user_pref})

@login_required_message
def edit_profile(request):
    if request.method == 'POST':
        form = UserProfileForm(request.POST, request.FILES, instance=request.user.userprofile)
        if form.is_valid():
            form.save()
            return redirect('settings')
    else:
        form = UserProfileForm(instance=request.user.userprofile)
    return render(request, 'linktastic/edit_profile.html', {'form': form})

@login_required_message
def customize_links(request):
    try:
        user_pref = UserLinkDisplayPreference.objects.get(user=request.user)
    except UserLinkDisplayPreference.DoesNotExist:
        user_pref = UserLinkDisplayPreference(user=request.user)

    if request.method == 'POST':
        form = UserLinkDisplayPreferenceForm(request.POST, instance=user_pref)
        if form.is_valid():
            form.save()
            messages.success(request, 'Link display preferences updated successfully.')
            return redirect('settings')
    else:
        form = UserLinkDisplayPreferenceForm(instance=user_pref)

    return render(request, 'linktastic/customize-links.html', {'form': form})

@login_required_message
def url_shortener(request):
    if request.method == 'POST':
        form = URLShortenerForm(request.POST)
        if form.is_valid():
            original_url = form.cleaned_data['original_url']
            shortened = ShortenedURL(original_url=original_url)
            shortened.save()  # First save to generate an id
            shortened.slug = shortened.generate_slug()  
            shortened.save()  # Save again to store the computed slug
            short_url = request.scheme + '://' + request.get_host() + reverse('redirect', args=[shortened.slug])
            return render(request, 'linktastic/url-shortener.html', {'form': form, 'short_url': short_url})

    else:
        form = URLShortenerForm()

    return render(request, 'linktastic/url-shortener.html', {'form': form})

BASE62_ALPHABET = "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"

def base62_decode(string, alphabet=BASE62_ALPHABET):
    base = len(alphabet)
    strlen = len(string)
    num = 0

    for idx, char in enumerate(string):
        power = (strlen - (idx + 1))
        num += alphabet.index(char) * (base ** power)

    return num

def redirect_view(request, slug):
    try:
        id = base62_decode(slug)
        obj = get_object_or_404(ShortenedURL, id=id)
    except ValueError:
        return HttpResponse('Invalid slug')
    except Http404:
        return HttpResponse(f'No ShortenedURL with id {id}')
    else:
        return redirect(obj.original_url)

linktastic/templates/linktastic/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <title>{% block title %}LinkTastic{% endblock %}</title> 
  <link href="{% static 'linktastic/normalize.css' %}" rel="stylesheet">
  <link href="{% static 'linktastic/webflow.css' %}" rel="stylesheet">
  <link href="{% static 'linktastic/rodrigos-ultra-awesome-site-8d58bf.webflow.css' %}" rel="stylesheet">
  {% block extra_style %}{% endblock extra_style %}
</head>
<body style="background-color: #cdb8a5">
  <main>
    {% for message in messages %}
    <div class="message {{ message.tags }}">{{ message }}</div>
    {% endfor %}
  </main>
  {% block content %}
  {% endblock %}
  {% block extra_script %}{% endblock extra_script %}
</body>
</html>

linktastic/templates/linktastic/change_password.html
{% extends 'linktastic/base.html' %}

{% load static %}

{% block content %}

{% block extra_style %}
<style>
  .form-container {
    width: 100%;
    max-width: 600px;
    margin: 0 auto;
    padding: 20px;
  }

  .form-title {
    text-align: center;
    margin-bottom: 20px;
    font-size: 24px;
  }

  .change-password-form .form-field {
    margin-bottom: 10px;
  }

  .change-password-form label {
    display: block;
    text-align: center;
    font-size: 18px;
    margin-bottom: 5px;
  }

  .change-password-form input {
    width: 100%;
    padding: 10px;
    font-size: 16px;
  }

  .submit-button {
    display: block;
    width: 100%;
    padding: 10px;
    font-size: 18px;
    background-color: #964B00;
    color: #fff;
    border: none;
    cursor: pointer;
    text-align: center;
  }

  .submit-button:hover {
    background-color: #763A00;
  }

  .field-error {
      color: red;
      font-size: 14px;
  }
</style>
{% endblock extra_style %}
<div class="form-container">
  <h1 class="form-title">Change Password</h1>

  <form method="post" class="change-password-form">
      {% csrf_token %}
      
      <div class="form-field">
          <label for="{{ form.old_password.id_for_label }}">Old Password</label>
          {{ form.old_password }}
          {% if form.old_password.errors %}
              <div class="field-error">{{ form.old_password.errors|join:", " }}</div>
          {% endif %}
      </div>

      <div class="password-help-text">
        {{ form.new_password1.help_text|safe }}
      </div>

      <div class="form-field">
          <label for="{{ form.new_password1.id_for_label }}">New Password</label>
          {{ form.new_password1 }}
          {% if form.new_password1.errors %}
              <div class="field-error">{{ form.new_password1.errors|join:", " }}</div>
          {% endif %}
      </div>

      <div class="form-field">
          <label for="{{ form.new_password2.id_for_label }}">Confirm New Password</label>
          {{ form.new_password2 }}
          {% if form.new_password2.errors %}
              <div class="field-error">{{ form.new_password2.errors|join:", " }}</div>
          {% endif %}
      </div>
      
      <button class="submit-button" type="submit">Change Password</button>
  </form>
  <br>
  <br>
  <a href="{% url 'settings' %}" class="submit-button">Return to Settings</a>
</div>
{% endblock %}

linktastic/templates/linktastic/customize-links.html
{% extends 'linktastic/base.html' %}

{% load static %}

{% block content %}
{% block extra_style %}
<style>
    body {
        background-color: #f8f8f8;
    }

    .container {
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        gap: 20px;
    }

    h1 {
        color: black;
    }

    label {
        display: block;
        text-align: center;
        font-size: 1.2em;
    }

    select {
        display: block;
        width: 200px;
        height: 40px;
        margin: 10px auto;
        font-size: 1.1em;
        padding-left: 10px;
    }

    button {
        background-color: #964b00;
        color: #ffffff;
        padding: 10px 20px;
        font-size: 1.5em;
        border-radius: 5px;
        margin-top: 20px;
        display: block;
        margin: auto;
    }

    button:hover {
        background-color: #253443;
    }
</style>
{% endblock extra_style %}

<body class="body-2">
    <div class="container">
        <h1>Customize Links</h1>
        <form method="POST">
          {% csrf_token %}

          <label for="font_size">Font Size:</label>
          <select name="font_size" id="font_size">
            <option value="12px">Small</option>
            <option value="16px">Medium</option>
            <option value="20px">Large</option>
          </select>

          <label for="font_color">Font Color:</label>
          <select name="font_color" id="font_color">
            <option value="black">Black</option>
            <option value="blue">Blue</option>
            <option value="red">Red</option>
          </select>

          <label for="button_shape">Button Shape:</label>
          <select name="button_shape" id="button_shape">
              <option value="SQUARE" {% if form.instance.button_shape == 'SQUARE' %}selected{% endif %}>Square</option>
              <option value="ROUNDED" {% if form.instance.button_shape == 'ROUNDED' %}selected{% endif %}>Rounded</option>
          </select>

          <label for="icon">Icon:</label>
          <select name="icon" id="icon">
              <option value="NONE" {% if form.instance.icon == 'NONE' %}selected{% endif %}>None</option>
              <option value="STAR" {% if form.instance.icon == 'STAR' %}selected{% endif %}>Star</option>
              <option value="HEART" {% if form.instance.icon == 'HEART' %}selected{% endif %}>Heart</option>
          </select>

          <button type="submit">Save Changes</button>
        </form>
    </div>
</body>

{% endblock %}

linktastic/templates/linktastic/customize-profile.html
{% extends 'linktastic/base.html' %}

{% load static %}

{% block content %}

<body>
    <div>
      <div class="rl_footer1_component">
        <div class="rl-padding-global-2">
          <div class="rl-container-large-2">
            <div class="rl-padding-section-medium">
              <div class="w-layout-grid rl_footer1_top-wrapper">
                <div class="rl_footer1_left-wrapper">
                  <div class="rl_footer1_spacing-block-1">
                    <div class="text-block-11">Current Profile</div>
                  </div>
                  <div class="rl-text-style-regular-2">Current profile holder<br>‍</div>
                  <div class="rl_footer1_spacing-block-2"></div>
                </div>
                <div class="w-layout-grid rl_footer1_menu-wrapper">
                  <div id="w-node-e71272f3-d1bc-85fe-e05a-99741eab019e-e9153761" class="rl_footer1_link-list">
                    <h2 class="rl-heading-style-h2-6">Settings</h2>
                    <div class="rl_footer1_spacing-block-4"></div>
                    <a href="#" class="button-3-copy-4 w-button">Remove Profile Picture</a>
                    <div class="rl_contact7_spacing-block-2"></div>
                    <a href="#" class="button-3 w-button">Change Profile Picture</a>
                    <div class="rl_contact7_spacing-block-2"></div>
                    <a href="#" class="button-3-copy-8 w-button">Change  Name</a>
                    <div class="rl_contact7_spacing-block-2"></div>
                    <a href="#" class="button-3-copy-7 w-button">Change Bio</a>
                  </div>
                </div>
              </div>
              <div class="rl_footer1_spacing-block-5"></div>
              <div class="rl_footer1_line-divider"></div>
              <div class="rl_footer1_spacing-block-6"></div>
              <div class="rl_footer1_bottom-wrapper">
                <div class="rl_footer1_credit-text">© 2022 Relume. All right reserved.</div>
                <div class="w-layout-grid rl_footer1_legal-list">
                  <a href="#" class="rl_footer1_legal-link">Privacy Policy</a>
                  <a href="#" class="rl_footer1_legal-link">Terms of Service</a>
                  <a href="#" class="rl_footer1_legal-link">Cookies Settings</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
</body>

{% endblock %}

linktastic/templates/linktastic/edit_profile.html
{% extends 'linktastic/base.html' %}

{% load static %}

{% block content %}

{% block extra_style %}
<style>
    body {
        text-align: center;
    }

    .field-title {
        font-size: 2em;
    }

    .field-description {
        font-size: 1.2em;
    }

    .input-large {
        height: 50px;
        width: 70%;
        margin: auto;
        font-size: 1.2em;
    }

    .input-small {
        height: 30px;
        width: 70%;
        margin: auto;
        font-size: 1.2em;
    }

    #id_profile_picture {
        display: none;
    }

    #profile_picture_label {
        cursor: pointer;
    }

    #profile_picture_preview {
        border-radius: 50%;
        width: 100px;
        height: 100px;
        object-fit: cover;
        display: block;
        margin-left: auto;
        margin-right: auto;
    }

    .btn-submit {
        background-color: #964b00;
        color: #ffffff;
        padding: 10px 20px;
        font-size: 1.5em;
        border-radius: 5px;
        margin-top: 20px;
    }
    input[type="file"] {
    display: none;  /* hide the default file input */
    }

    .custom-file-upload {
        position: relative;
        display: inline-block;
        padding: 10px 16px;
        background: #f4f4f4;
        cursor: pointer;
        margin-bottom: 10px;
        border-radius: 4px;
        border: 1px solid #ddd;
    }

    .custom-file-upload:hover {
        background: #e4e4e4;
    }

    .custom-file-upload label {
        margin: 0;  /* remove default browser margins */
    }

</style>
{% endblock extra_style %}
<body style="background-color: #cdb8a5;">

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}

    <br>
    <div class="field-title">Display Name</div>
    <br>
    {{ form.display_name }}
    <br>

    <br>
    <div class="field-title">Bio</div>
    <br>
    {{ form.bio }}

    <br>
    <br>
    <div class="field-title">Profile Picture</div>
    <br>
    <div class="field-description">Pictures should be squared dimensions for best looks</div>
    <br>
    <div class="custom-file-upload">
        <input type="file" name="{{ form.profile_picture.name }}" id="id_profile_picture" onchange="readURL(this);">
        <label for="id_profile_picture">Choose a profile picture</label>
    </div>

    <img id="profile_picture_preview" src="{% if form.instance.profile_picture %}{{ form.instance.profile_picture.url }}{% else %}{% static 'linktastic/default-profile-picture.jpg' %}{% endif %}" onerror="this.src='{% static 'linktastic/default-profile-picture.jpg' %}';">

    <button class="btn-submit" type="submit">Save Changes</button>
</form>
<br>
<br>
<br>
<a href="{% url 'settings' %}" class="btn-submit">Return to Settings</a>


{% block extra_script %}
<script>
    document.querySelector('#id_profile_picture').addEventListener('change', function(event) {
        var reader = new FileReader();
        reader.onload = function() {
            var output = document.querySelector('#profile_picture_preview');
            output.src = reader.result;
        };
        reader.readAsDataURL(event.target.files[0]);
    });
</script>
{% endblock extra_script %}

</body>
{% endblock %}

linktastic/templates/linktastic/home.html
{% extends 'linktastic/base.html' %}

{% load static %}

{% block content %}

<div>
  <div data-animation="default" data-collapse="medium" data-duration="400" data-easing="ease" data-easing2="ease" role="banner" class="navbar-logo-left-container-2 shadow-three w-nav">
    <div class="container-2"></div>
    <div class="navbar-wrapper-2"><img src="{% static 'linktastic/images/Screenshot-2023-07-08-at-3.25.39-PM.png' %}" loading="lazy" width="330" sizes="(max-width: 479px) 40vw, 330px" alt="" class="image-3">
      <nav role="navigation" class="nav-menu-wrapper-2 w-nav-menu"></nav>
      <div class="menu-button-2 w-nav-button"></div>
      <a href="{% url 'login' %}" class="button-primary-2 w-button">Register / Login</a>
    </div>
  </div>
  <section class="hero-heading-left wf-section">
    <h1 class="heading">Custom links home page and URL shortener. All in one. Completely free.</h1>
    <p class="margin-bottom-24px">Seamless design on both desktop and mobile devices</p><img src="{% static 'linktastic/images/linktastic_landing_3.png' %}" loading="lazy" width="800" sizes="(max-width: 767px) 94vw, 800px" alt="" class="image-4">
  </section>
</div>

{% endblock %}

linktastic/templates/linktastic/login.html
{% extends 'linktastic/base.html' %}

{% load static %}
{% load static widget_tweaks %}

{% block content %}

{% block extra_style %}
<style>
.form-container {
    display: flex;
    flex-direction: column;
    align-items: center;
}
.form-field {
    width: 80%;
    margin-bottom: 20px;
    font-size: 18px;
}
.form-label {
    text-align: center;
    font-size: 22px;
    margin-bottom: 10px;
}
.submit-button {
    width: 50%;
    padding: 10px;
    background-color: #A52A2A;
    color: white;
    font-size: 18px;
    cursor: pointer;
    border: none;
    border-radius: 5px;
}
.submit-button:hover {
    background-color: #8B4513;
}
.register-button {
    display: inline-block;
    background-color: #f8f9fa;
    color: #A52A2A;
    text-align: center;
    padding: 10px;
    margin: 20px 0;
    border: 1px solid #A52A2A;
    border-radius: 5px;
    text-decoration: none;
}
.register-button:hover {
    color: white;
    background-color: #A52A2A;
}

</style>
{% endblock extra_style %}
<body>
    <div>
        <section class="wf-section">
            <section class="rl_section_contact1">
                <div class="rl-padding-global">
                    <div class="rl-container-small">
                        <div class="rl-padding-section-large">
                            <div class="rl_contact1_component">
                                <div class="rl_contact1_heading-wrapper">
                                    <div class="rl-text-style-subheading">Login</div>
                                    <img src="{% static 'linktastic/images/Screenshot-2023-07-08-at-3.56.20-PM.png' %}" loading="lazy" width="493" sizes="(max-width: 767px) 90vw, 493px" alt="">
                                    <div class="rl_contact1_spacing-block-1"></div>
                                    <h2 class="rl-heading-style-h2">Welcome back!</h2>
                                    <div class="rl_contact1_spacing-block-2"></div>
                                </div>
                                <div class="rl_contact1_spacing-block-3"></div>
                                <div class="rl_contact1_form-block w-form">
                                    <form method="post" class="form-container">
                                        {% csrf_token %}
                                        {% if form.non_field_errors %}
                                            <div class="error-messages">
                                                {% for error in form.non_field_errors %}
                                                    <p>{{ error }}</p>
                                                {% endfor %}
                                            </div>
                                        {% endif %}
                                        <label for="{{ form.username.id_for_label }}" class="form-label">{{ form.username.label }}</label>
                                        {{ form.username|add_class:"form-field" }}
                                        <div class="password-help-text">
                                            {{ form.username.help_text|safe }}
                                        </div>
                                        <label for="{{ form.password.id_for_label }}" class="form-label">{{ form.password.label }}</label>
                                        {{ form.password|add_class:"form-field" }}
                                        <div class="password-help-text">
                                            {{ form.password.help_text|safe }}
                                        </div>
                                        <button type="submit" class="submit-button">Login</button>
                                    </form>
                                    <div class="rl-success-message w-form-done">
                                        <div class="rl-success-text">Thank you! Your submission has been received!</div>
                                    </div>
                                    <div class="rl-error-message w-form-fail">
                                        <div class="rl-error-text">Oops! Something went wrong while submitting the form.</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <a href="{% url 'register' %}" class="register-button">
                        Don't have an account yet? Click here to register
                    </a>
                </div>
            </section>
        </section>
    </div>
</body>
{% endblock %}

linktastic/templates/linktastic/password_change_done.html
{% extends 'linktastic/base.html' %}

{% load static %}

{% block content %}

<p>Password changed successfully! You will be redirected to the login page in 3 seconds...</p>

<script>
    setTimeout(function(){
        window.location.href = "{% url 'login' %}";
    }, 3000);
</script>

{% endblock %}